Resources:
  CloudBuildProject:
    Type: 'AWS::CodeBuild::Project'
    Properties: 
        Name: !Ref AWS::StackName
        ServiceRole:

  CloudBuildServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
  CodeBuildSourceCredential:
    Type: 'AWS::CodeBuild::SourceCredential'
    Properties:
        AuthType: GITHUB_TOKEN
        Se
  
  
    
